### ISSUE TITLE
Macro MMAP_BLOCK_SIZE has no parentheses

### ISSUE THREAD

**Issue by BForever** [wengkai/stm32isp#2]
There's no parentheses in the definition of macro MMAP_BLOCK_SIZE in the 11th line of file memmap.h : 
`#define MMAP_BLOCK_SIZE 4*1024`
Which leads to an error in the execution of 
`pBlock->address = address/MMAP_BLOCK_SIZE*MMAP_BLOCK_SIZE;  `
It equals
`pBlock->address = address/4*1024*4*1024`

So the macro should be modified to
`#define MMAP_BLOCK_SIZE (4*1024)`

**Comment by wengkai** [comment]
odd bug solved a year ago
